TTS/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;
using System.Web.Mvc;
using TTS.Models;

namespace TTS.Controllers
{
    public class ManagementController : Controller
    {
        //
        // GET: /Management/

        public ActionResult Index()
        {
            return View();
        }

        //*************  User  ********************
        public ActionResult User(string user_name, string user_fist_name, string user_last_name)
        {
            Models.User u = new User();
            return View(u.getUser(user_name, user_fist_name, user_last_name));
        }

        public ActionResult User_Add()
        {
            Models.UserModel u = new UserModel();
            Models.UserGroup ug = new UserGroup();
            u.UserGroup = function.ToSelectList(ug.getUserGroup_dt("", ""), "user_group_id", "name");
            return View("User_Edit", u);
        }

        public ActionResult User_Edit(string id)
        {
            Models.User u = new User();
            return View(u.getUser_userID(id));
        }

        public ActionResult User_Update(string user_id, string name, string first_name, string last_name, string password, string user_group_id)
        {
            Models.User u = new User();
            var Result = u.updateUser(user_id, name, first_name, last_name, password, user_group_id);
            if (Result.ResultCode == 0)
            {
                return RedirectToAction("User");
            }
            else
                return RedirectToAction("User_Edit", new { id = user_id, msg = Result.MessageText });//Return Error 
        }


        //*************  User Group  ********************
        public ActionResult UserGroup(string group_name, string group_desc)
        {
            Models.UserGroup u = new UserGroup();
            return View(u.getUserGroup(group_name, group_desc));
        }

        public ActionResult UserGroup_Add()
        {
            Models.UserGroupModel u = new UserGroupModel();
            return View("UserGroup_Edit", u);
        }

        public ActionResult UserGroup_Edit(string id)
        {
            Models.UserGroup u = new UserGroup();
            return View(u.getUserGroup_groupID(id));
        }

        public ActionResult UserGroup_Update(string user_group_id, string name, string description)
        {
            Models.UserGroup u = new UserGroup();
            var Result = u.updateUserGroup(user_group_id, name, description);
            if (Result.ResultCode == 0)
            {
                return RedirectToAction("UserGroup");
            }
            else
                return RedirectToAction("UserGroup_Edit", new { id = user_group_id, msg = Result.MessageText });//Return Error 
        }
        public ActionResult UserGroup_Delete(string id)
        {
            Models.UserGroup u = new UserGroup();
            u.deleteUserGroup(id);
            return View("UserGroup", u.getUserGroup("", ""));
        }




        //*************  User Authentication  ********************
        public ActionResult Authorize()
        {
            Models.UserModel u = new UserModel();
            Models.UserGroup ug = new UserGroup();
            u.UserGroup = function.ToSelectList(ug.getUserGroup_dt("", ""), "user_group_id", "name");
            return View(u);
        }


        [HttpGet]
        public ActionResult Authorize_Edit(string id)
        {
            #region Example
            // ตัวอย่าง
            // List<AuthorizeParentMenuModel> model = new List<AuthorizeParentMenuModel>();
            // AuthorizeParentMenuModel firstAuthor = new AuthorizeParentMenuModel
            // {
            //     menu_id = "111111",
            //     menu_name = "John",
            //     is_active = true,
            //     AuthorizeChildMenuModel = new List<AuthorizeChildMenuModel>{  
            //         new AuthorizeChildMenuModel{  
            //             menu_id="00001",  
            //             menu_name = "User",
            //             is_active = true
            //         }, new AuthorizeChildMenuModel{
            //             menu_id="00002",
            //             menu_name = "UserGroup",
            //             is_active = true  
            //         } , new AuthorizeChildMenuModel{  
            //             menu_id="00003",  
            //             menu_name = "Assign",  
            //             is_active = true  
            //         }  
            //     }
            // };
            // AuthorizeParentMenuModel secAuthor = new AuthorizeParentMenuModel
            //{
            //    menu_id = "2222",
            //    menu_name = "SalesOrder",
            //    is_active = true,

            //};
            // AuthorizeParentMenuModel trdAuthor = new AuthorizeParentMenuModel
            //{
            //    menu_id = "3333",
            //    menu_name = "Return",
            //    is_active = false

            //};

            // model.Add(firstAuthor);
            // model.Add(secAuthor);
            // model.Add(trdAuthor);
            #endregion

            Authorize auth = new Authorize();
            return View("Authorize_Edit", auth.getUserGroupMenu(id));
        }

        [HttpPost]
        public ActionResult Authorize_Edit(List<AuthorizeParentMenuModel> model)
        {
            List<AuthorizeParentMenuModel> selectedParent = model.Where(a => a.is_active).ToList();
            List<AuthorizeChildMenuModel> selectedChild = model.Where(a => a.is_active)
                                                .SelectMany(a => a.AuthorizeChildMenuModel.Where(b => b.is_active)).ToList();
            return View();
        }


        [HttpPost]
        public ActionResult Authorize_Update(FormCollection collection)
        {
            string strGoup_menu_id = Request.Params["id"];
            string[] arrResultChk;
            List<Models.AuthorizeParentMenuModel> lsPost = new List<Models.AuthorizeParentMenuModel>();

            //string strResult = "";
            arrResultChk = collection.GetValues("chk");

            //form post to List
            foreach (string s in Request.Params.Keys)
            {
                var IsMatch = Array.FindAll(arrResultChk, a => a.Equals(s.ToString()));
                if (IsMatch.Length > 0)
                {
                    //strResult += "name : " + s.ToString() + ", Value : " + Request.Params[s] + "\r\n";
                    Models.AuthorizeParentMenuModel apModel = new AuthorizeParentMenuModel();
                    apModel.menu_group_id = Request.Params["id"];
                    apModel.menu_id = s.ToString();
                    apModel.str_is_active = Request.Params[s];
                    lsPost.Add(apModel);
                }
            }

            //Array MenuID to List
            for (int i = 0; i < arrResultChk.Length; i++)
            {
                var IsMatch = lsPost.Find(x => x.menu_id == arrResultChk[i]);
                if (IsMatch == null) //Insert 'no' isNull
                {
                    Models.AuthorizeParentMenuModel apModel = new AuthorizeParentMenuModel();
                    apModel.menu_group_id = Request.Params["id"];
                    apModel.menu_id = arrResultChk[i];
                    apModel.str_is_active = "false";
                    lsPost.Add(apModel);
                }
            }

            Models.Authorize au = new Models.Authorize();

            var Result = au.updateUserGroupMenu(lsPost);
            if (Result.ResultCode == 0)
            {
                return RedirectToAction("Authorize");
            }
            else
                return RedirectToAction("Authorize_Edit", new { id = strGoup_menu_id, msg = Result.MessageText });//Return Error 
        }


        //[HttpPost]
        //public ActionResult Authorize_Update(FormCollection collection)
        //{
        //    try
        //    {
        //        string[] test = collection.GetValues("chkAuth");
        //    }
        //    catch (Exception ex)
        //    {
        //        return null;
        //    }
        //    return View();
        //}


        //public JsonResult UserGroup()
        //{
        //    var vm = clients.AsQueryable();
        //    var ajaxGridFactory = new Grid.Mvc.Ajax.GridExtensions.AjaxGridFactory();
        //    var grid = ajaxGridFactory.CreateAjaxGrid(vm, 1, false);
        //}

        //public JsonResult PersonsPaged(int page)
        //{
        //    var vm = clients.AsQueryable();
        //    var ajaxGridFactory = new Grid.Mvc.Ajax.GridExtensions.AjaxGridFactory();
        //    var grid = ajaxGridFactory.CreateAjaxGrid(vm, page, true);
        //}
    }
}

TTS/Views/Management/Authorize.cshtml
@model TTS.Models.UserModel

@{
    ViewBag.Title = "กำหนดสิทธิ์การใช้งาน";
    ViewBag.PageTitle = "กำหนดสิทธิ์การใช้งาน";
    ViewBag.PageDesc = "Authenticate Users";
}

<div class="panel-group" id="accordion" role="tablist">
    <div class="panel panel-success">
        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title inline">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    <i class="fa fa-search"></i> ตัวเลือก
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse " role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                @using (Html.BeginForm("Authorize", "Management", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="form-group form-group-sm">
                        <label for="inputEmail3" class="col-sm-2 control-label">กลุ่มผู้ใช้</label>
                        <div class="col-sm-4">
                            @Html.DropDownListFor(a => a.user_group_id, new SelectList(Model.UserGroup, "Value", "Text", Request.QueryString["id"]), new { id = "U_id", @class = "form-control", Name = "id" })
                        </div>

                        <div class="col-sm-4">
                            <button class="btn btn-primary btn-sm" type="submit"><i class="fa fa-search"></i> แสดง</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@if (Request.QueryString["id"] != null)
{
    @section styles{
        @Styles.Render("~/Content/plugins/Bootstrap-Tree-View/TreeView.css")
    }
    
    Html.RenderAction("Authorize_Edit");
    
    @section Scripts
    {
        <script src="~/Content/plugins/Bootstrap-Tree-View/TreeView.js"></script>
    }
}

TTS/Views/Management/Authorize_Edit.cshtml
@model List<TTS.Models.AuthorizeParentMenuModel>

@{Layout = null;}

@if (Request.QueryString["msg"] != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>บันทึกข้อมูลไม่สำเร็จ!</strong> : @Request.QueryString["msg"].ToString()
    </div>
}

<div class="panel panel-primary">
    <div class="panel-heading panel-head">Assign authenticate users</div>
    <div id="frm-author" class="panel-body">
        @using (Html.BeginForm("Authorize_Update", "Management", FormMethod.Post,
                                      new { enctype = "multipart/form-data" }))
        {
            <div class="tree">

                @for (int i = 0; i < Model.Count(); i++)
                {
                    @Html.Hidden("chk",  @Model[i].menu_id); //post All ID
        
                    <ul>
                        <li>
                            <a href="#">
                                @Html.CheckBoxFor(model => model[i].is_active, new { @class = "tree-checkbox parent", @id = @Model[i].menu_id, Name = @Model[i].menu_id })

                                @*@Html.HiddenFor(model => model[i].is_active, new { Name = @Model[i].menu_id })*@

                                <label for=@i>
                                    @Html.DisplayFor(model => model[i].menu_name)
                                </label>
                            </a>
                            <ul>
                                @for (int j = 0; j < Model[i].AuthorizeChildMenuModel.Count(); j++)
                                {
                                    int k = 1 + j;
                                    @*@Html.HiddenFor(model => model[i].AuthorizeChildMenuModel[j].menu_id)*@
                                    @Html.Hidden("chk", @Model[i].AuthorizeChildMenuModel[j].menu_id);

                                    <li>
                                        <a href="#">
                                            @Html.CheckBoxFor(model => model[i].AuthorizeChildMenuModel[j].is_active, new { @class = "tree-checkbox node-item", @iid = i + "" + j, @id = @Model[i].AuthorizeChildMenuModel[j].menu_id, Name = @Model[i].AuthorizeChildMenuModel[j].menu_id })

                                            <label for=@i@j>
                                                @Html.DisplayFor(model => model[i].AuthorizeChildMenuModel[j].menu_name)
                                            </label>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                }
            </div>

            <input type="hidden" name="id" value="@Request.QueryString["id"]" />

            <row style="padding-top:20px;">
                <div class="form-group">
                    <div class="col-lg-9"></div>
                    <div class="col-lg-3 text-center">
                        <button class="btn btn-success" id="btnSubmit" type="submit">
                            <i class="fa fa-save"></i>
                            บันทึก
                        </button>
                    </div>
                </div>
            </row>
        }

    </div>
</div>

TTS/Views/Management/User.cshtml
@model IEnumerable<TTS.Models.UserModel>

@using GridMvc.Html
@using GridMvc.Sorting


@{
    ViewBag.Title = "ผู้ใช้งาน";
    ViewBag.PageTitle = "ผู้ใช้งาน";
    ViewBag.PageDesc = "User";
}

@if (Request.QueryString["actions"] == null)
{

    <div class="panel-group" id="accordion" role="tablist">
        <div class="panel panel-success">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title inline">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        <i class="fa fa-search"></i> ตัวเลือกค้นหา
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    @using (Html.BeginForm("User", "Management", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <div class="form-group form-group-sm">
                            <label for="inputEmail3" class="col-sm-2 control-label">User Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="user_name">
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="inputPassword3" class="col-sm-2 control-label">First Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="user_fist_name">
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="inputPassword3" class="col-sm-2 control-label">Last Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="user_last_name">
                            </div>
                        </div>

                        <div class="form-group" style="margin-bottom:0;">
                            <div class="col-md-4 text-left">

                            </div>
                            <div class="col-md-4 text-center"></div>
                            <div class="col-md-4 text-right"><button class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button></div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success btn-sm" role="button" href="@Url.Action("User", "Management", new { actions = "Add" })"><i class="fa fa-plus"></i>  เพิ่มใหม่</a>
        </div>
    </div>

    @Html.Grid(Model).Columns(columns =>
                    {

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link => @<a class="btn btn-warning btn-xs" href="@Url.Action("User", "Management", new
                                                                                           {
                                                                                               id = link.user_id,
                                                                                               actions="Edit",
                                                                                               returnUrl = ViewContext.HttpContext.Request.Url.PathAndQuery
                                                                                           }, null)" role="button" title="แก้ไข" name="btn_Edit"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>)
                                .Titled("แก้ไข")
                                .Css("text-center").Css("nosort");

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link => @<a class="btn btn-danger btn-xs link_delete" name="btn_Delete" id="ln-@Html.Encode(link.user_id)" href="@Url.Action("Delete", "User", new
                                                                                          {
                                                                                              id = link.user_id,
                                                                                              returnUrl = ViewContext.HttpContext.Request.Url.PathAndQuery
                                                                                          }, null)" role="button" title="ลบ"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>)
                                .Titled("ลบ")
                                .Css("text-center").Css("nosort");

                        columns.Add(c => c.user_id).Titled("User ID");
                        columns.Add(c => c.name).Titled("User Name");
                        columns.Add(c => c.first_name).Titled("First Name");
                        columns.Add(c => c.last_name).Titled("Last Name");
                        //columns.Add(c => c.locale_id).Titled("Local");
                        //columns.Add(c => c.is_active).Titled("Active");
                        columns.Add(c => c.create_date).Titled("Create Date");
                    })

    //End If
}
else
{
    <div id="div_edit">
        @{
    if (Request.QueryString["actions"].ToString() == "Edit")
    {
        Html.RenderAction("User_Edit");
    }
    else if (Request.QueryString["actions"].ToString() == "Add")
    {
        Html.RenderAction("User_Add");
    }
        }
    </div>
}


@section Scripts
{
    <script>
        $(function () {
            var oTable = $('.table').DataTable({
                "autoWidth": false,
                "aaSorting": [[2, 'asc']],
                "dom": '<"top.pull-right"l>rt<"row"<"col-md-6"i><"col-md-6"p>> <"clear">',
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': ['nosort']
                }]
            });

        });
    </script>

    <script src="~/Scripts/Script_Action.js"></script>
}

TTS/Views/Management/UserGroup.cshtml
@model IEnumerable<TTS.Models.UserGroupModel>

@using GridMvc.Html
@using GridMvc.Sorting


@{
    ViewBag.Title = "กลุ่มผู้ใช้";
    ViewBag.PageTitle = "กลุ่มผู้ใช้";
    ViewBag.PageDesc = "User Group";
}

@if (Request.QueryString["actions"] == null)
{
    <div class="panel-group" id="accordion" role="tablist">
        <div class="panel panel-success">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title inline">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        <i class="fa fa-search"></i> ตัวเลือกค้นหา
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    @using (Html.BeginForm("UserGroup", "Management", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <div class="form-group form-group-sm">
                            <label for="inputEmail3" class="col-sm-2 control-label">Group Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="group_name">
                            </div>
                        </div>
                        <div class="form-group form-group-sm">
                            <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="group_desc">
                            </div>
                        </div>

                        <div class="form-group" style="margin-bottom:0;">
                            <div class="col-md-4 text-left">

                            </div>
                            <div class="col-md-4 text-center"></div>
                            <div class="col-md-4 text-right"><button class="btn btn-primary btn-sm"><i class="fa fa-search"></i> ค้นหา</button></div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success btn-sm" role="button" href="@Url.Action("UserGroup", "Management", new { actions = "Add" })"><i class="fa fa-plus"></i>  เพิ่มใหม่</a>
        </div>
    </div>


    @Html.Grid(Model).Columns(columns =>
                    {

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link => @<a class="btn btn-warning btn-xs" href="@Url.Action("UserGroup", "Management", new
                                                                                           {
                                                                                               id = link.user_group_id,
                                                                                               actions="Edit",
                                                                                               returnUrl = ViewContext.HttpContext.Request.Url.PathAndQuery
                                                                                           }, null)" role="button" title="แก้ไข" name="btn_Edit"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>)
                                .Titled("แก้ไข")
                                .Css("text-center").Css("nosort");

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link => @<a class="btn btn-danger btn-xs link_delete" name="btn_Delete" id="ln-@Html.Encode(link.user_group_id)" href="@Url.Action("UserGroup_Delete", "Management", new
                                                                                          {
                                                                                              id = link.user_group_id,
                                                                                              returnUrl = ViewContext.HttpContext.Request.Url.PathAndQuery
                                                                                          }, null)" role="button" title="ลบ"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>)
                                .Titled("ลบ")
                                .Css("text-center").Css("nosort");


                        columns.Add(c => c.name).Titled("Name");
                        columns.Add(c => c.description).Titled("Description");
                        columns.Add(c => c.is_active).Titled("Active");
                        columns.Add(c => c.create_date).Titled("Create Date");
                        //columns.Add(c => c.user_group_id).Titled("User Group");
                    })
    //End If
}
else
{

    <div id="div_edit">
        @{
    if (Request.QueryString["actions"].ToString() == "Edit")
    {
        //if (Request.QueryString["actions"].ToString() == "Add")
        //    TTS.Models.UserGroupModel = null;

        Html.RenderAction("UserGroup_Edit");
    }
    else if (Request.QueryString["actions"].ToString() == "Add")
    {
        Html.RenderAction("UserGroup_Add");
    }

        }
    </div>

}


@section Scripts
{
    <script>
        $(function () {
            var oTable = $('.table').DataTable({
                "autoWidth": false,
                "aaSorting": [[2, 'asc']],
                "dom": '<"top.pull-right"l>rt<"row"<"col-md-6"i><"col-md-6"p>> <"clear">',
                'aoColumnDefs': [{
                    'bSortable': false,
                    'aTargets': ['nosort']
                }]
            });

        });
    </script>


    <script src="~/Scripts/Script_Action.js"></script>
}

TTS/Views/Management/UserGroup_Edit.cshtml
@model TTS.Models.UserGroupModel

@{Layout = null;}

@if (Request.QueryString["msg"] != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>บันทึกข้อมูลไม่สำเร็จ!</strong> : @Request.QueryString["msg"].ToString()
    </div>
}

@using (Html.BeginForm("UserGroup_Update", "Management", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.user_group_id)</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(a => a.user_group_id, new { @class = "form-control", disabled = "disabled" })
        </div>
    </div>
    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.name)</label>
        <div class="col-sm-10">
            @*<input type="password" class="form-control" id="input2" placeholder="Password">*@
            @Html.TextBoxFor(a => a.name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.description)</label>
        <div class="col-sm-10">
            @Html.TextAreaFor(a => a.description, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-12 text-center">
            <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> บันทึก</button>
            <a class="btn btn-danger" role="button" href="@Url.Action("UserGroup")"><i class="fa fa-times"></i> ยกเลิก</a>
        </div>
    </div>
}

TTS/Views/Management/User_Edit.cshtml
@model TTS.Models.UserModel

@{Layout = null;}

@if (Request.QueryString["msg"] != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>บันทึกข้อมูลไม่สำเร็จ!</strong> : @Request.QueryString["msg"].ToString()
    </div>
}

@using (Html.BeginForm("User_Update", "Management", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.user_id)</label>
        <div class="col-sm-10">
            @{  object displayMode = (Model.user_id == null ? (object)new { @class = "form-control" } : new { @class = "form-control", @readonly = "true" });
                @Html.TextBoxFor(a => a.user_id, displayMode)
            }
        </div>
    </div>
    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.name)</label>
        <div class="col-sm-10">
            @*<input type="password" class="form-control" id="input2" placeholder="Password">*@
            @Html.TextBoxFor(a => a.name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.first_name)</label>
        <div class="col-sm-10">
            @Html.TextAreaFor(a => a.first_name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.last_name)</label>
        <div class="col-sm-10">
            @Html.TextAreaFor(a => a.last_name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.password)</label>
        <div class="col-sm-10">
            @Html.PasswordFor(a => a.password, new {value = Model.password, @class = "form-control" })
            @Html.ValidationMessageFor(a => a.password)
        </div>
    </div>

    <div class="form-group">
        <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.user_group_id)</label>
        <div class="col-sm-10">
            @Html.DropDownListFor(a => a.user_group_id, Model.UserGroup, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-12 text-center">
            <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> บันทึก</button>
            <a class="btn btn-danger" role="button" href="@Url.Action("User")"><i class="fa fa-times"></i> ยกเลิก</a>
        </div>
    </div>
}