TTS/Controllers/ProcessController.cs
using DataLibrary;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TTS.Models;

namespace TTS.Controllers
{
    public class ProcessController : Controller
    {
        //
        // GET: /Process/

        public ActionResult Index()
        {
            return View();
        }

        #region SalesOrder

        //public ActionResult SalesOrder(string id, string period_start, string period_end, string branch, string productID, string size, string productName, string IsExport)
        //{
        //    //Models.Branch b = new Models.Branch();
        //    //ViewBag.ListBranch = b.getBranchAll();

        //    //Models.Size s = new Models.Size();
        //    //ViewBag.ListSize = s.getSize();

        //    Models.SalesOrder so = new Models.SalesOrder();
        //    return View(so.getSalesOrder(id, (branch == "?" ? "" : branch), productID, (size == "?" ? "" : size), period_start, period_end, IsExport));
        //}

        public ActionResult SalesOrder(string bid, string start, string stop)
        {
            //Models.Branch b = new Models.Branch();
            //ViewBag.ListBranch = b.getBranchAll();

            //Models.Size s = new Models.Size();
            //ViewBag.ListSize = s.getSize();

            Models.SalesOrder so = new Models.SalesOrder();
            return View(so.getSalesOrderByBranch(bid, start, stop));
        }

        public JsonResult getSalesOrder(string custGroup, string branchCode, string start, string stop)
        {
            Models.SalesOrder so = new Models.SalesOrder();
            return new JsonResult { Data = so.getSalesOrder(custGroup, branchCode, start, stop), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult SalesOrder_Edit(string i, string p, string s)
        {
            Models.SalesOrderModel sm = new SalesOrderModel();
            Models.SalesOrder so = new Models.SalesOrder();
            sm = so.getSalesOrderDetail(i, p, s);
            if (sm == null)
            {
                return View("SalesOrder");
            }
            else
                return View();
        }

        public ActionResult SalesOrder_Discount()
        {
            Models.Size si = new Models.Size();
            Models.SalesOrderModel s = new Models.SalesOrderModel();
            s.Size = si.getSize();

            //Models.GP gp = new Models.GP();
            //s.Size = gp.getGP();

            return View();
        }
        public ActionResult SalesOrder_DiscountExtra()
        {
            //Models.Size si = new Models.Size();
            //Models.SalesOrderModel s = new Models.SalesOrderModel();
            //s.Size = si.getSize();
            return View();
        }

        //[HttpPost]
        public ActionResult Branch()
        {
            Models.Branch b = new Models.Branch();
            b.getBranchAll();
            //List<Models.BranchModel> selectedBranch = model.ToList();
            return PartialView("~/Views/UserControl/ListBranch.cshtml", b);
        }

        public JsonResult getSalesOrderDetail(string id, string p, string s)
        {
            Models.SalesOrder so = new Models.SalesOrder();
            return new JsonResult { Data = so.getSalesOrderDetail(id, p, s), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getCustCode()
        {
            Models.Branch b = new Models.Branch();
            return new JsonResult { Data = (List<Models.BranchModel>)b.getCustGroup(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getBranch()
        {
            Models.Branch b = new Models.Branch();
            return new JsonResult { Data = (List<Models.BranchModel>)b.getBranchList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getBranchByCustGroup(string CustGroupCode)
        {
            Models.Branch b = new Models.Branch();
            return new JsonResult { Data = (List<Models.BranchModel>)b.getBranchList(CustGroupCode), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getSize()
        {
            Models.Size s = new Models.Size();
            return new JsonResult { Data = (List<Models.SizeModel>)s.getSizeList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getCoupon()
        {
            Discount d = new Discount();
            return new JsonResult { Data = (List<DiscountModel>)d.getCouponList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getCouponByCode(string b)
        {
            Discount d = new Discount();
            return new JsonResult { Data = (List<DiscountModel>)d.getCouponList(b), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getCouponExtra()
        {
            Discount d = new Discount();
            return new JsonResult { Data = (List<DiscountModel>)d.getCouponExtraList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getCouponExtraByCode(string b)
        {
            Discount d = new Discount();
            return new JsonResult { Data = (List<DiscountModel>)d.getCouponExtraList(b), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public JsonResult getGP(string BranchCode)
        {
            GP g = new GP();
            return new JsonResult { Data = (List<GPModel>)g.getGPList(BranchCode), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getDiscountOnTop(string OrderNumber, string LineNumber)
        {
            SalesOrder s = new SalesOrder();
            return new JsonResult { Data = (List<SalesOrderModel>)s.getDiscountOnTop(OrderNumber, Convert.ToInt32(LineNumber)), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getDiscountExtra(string OrderNumber, string LineNumber)
        {
            SalesOrder s = new SalesOrder();
            return new JsonResult { Data = (List<SalesOrderModel>)s.getDiscountExtra(OrderNumber, Convert.ToInt32(LineNumber)), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public ActionResult SalesOrder_Update(FormCollection frm)
        {
            SalesOrder sales = new Models.SalesOrder();
            DataTable dtSalesDT = sales.getSalesOrderDetailTable();
            DataTable dtDiscountOnTopDT = sales.getDiscountOnTopTable();
            DataTable dtDiscountExtraDT = sales.getDiscountExtraTable();

            #region SalesOrder
            //  OrderNumber, LineNumber, InvoiceNumber, ProductId, Size, Price, Cost, DiscountPer
            //, Discount, DiscountOnTop, GP, Qty, PriceTotal, Vat, LineTotal, CreateBy
            //, CreateDate, UpdateBy, UpdateDate, IsExport, RefNumber, Style, DocDate, GPCode
            dtSalesDT.Rows.Add(frm["OrderNumber"], frm["LineNumber"], frm["InvoiceNumber"], frm["ProductId"], frm["Size"], frm["Price"], frm["Price"], frm["DiscountPer"]
                             , frm["Discount"], frm["DiscountOnTop"], frm["GP"], frm["Qty"], frm["PriceTotal"], frm["Vat"], frm["LineTotal"], ""
                             , DateTime.Now, "", DateTime.Now, frm["IsExport"], frm["RefNumber"], frm["Style"], frm["DocDate"], frm["GPCode"]);

            #endregion

            #region Discount

            string[] arrResultDiscount = frm.GetValues("OrderDiscount[]");
            string[] arrResultDiscountExtra = frm.GetValues("OrderDiscountExtra[]");

            if (arrResultDiscount != null)
            {
                for (int i = 0; i < arrResultDiscount.Length; i++)
                {
                    string[] arr = arrResultDiscount[i].Split('|');
                    if (arr[0] != null || arr[0] != "")
                        dtDiscountOnTopDT.Rows.Add(frm["OrderNumber"], frm["LineNumber"], frm["LineNumber"], arr[0], arr[1], arr[2], arr[3], frm["GP"]);
                }
            }

            if (arrResultDiscountExtra != null)
            {
                for (int i = 0; i < arrResultDiscountExtra.Length; i++)
                {
                    string[] arr = arrResultDiscountExtra[i].Split('|');
                    if (arr[0] != null || arr[0] != "")
                        dtDiscountExtraDT.Rows.Add(frm["OrderNumber"], frm["LineNumber"], frm["LineNumber"], arr[0], arr[1], arr[2], arr[3], frm["GP"], "I");
                }
            }

            #endregion

            string result = sales.updateSalesOrder(dtSalesDT.Rows[0], dtDiscountOnTopDT, dtDiscountExtraDT);
            if (result == "")
                return RedirectToAction("SalesOrder");
            else
                return RedirectToAction("SalesOrder_Edit", new { i = frm["OrderNumber"], p = frm["ProductId"], s = frm["Size"], g = frm["Branch"], msg = result });
        }


        public ActionResult SalesOrder_Delete(string i, string p, string s, string returnUrl)
        {
            SalesOrder sales = new Models.SalesOrder();
            DataTable dtSalesDT = sales.getSalesOrderDetailDt(i, p, s);
            sales.deleteSalesOrder(dtSalesDT.Rows[0]);
            return View("SalesOrder");
        }


        //public JsonResult SalesOrder_Send(FormCollection frm)
        //{
        //    string[] arrResultSend = frm.GetValues("chk[]");
        //    DataTable dt = new DataTable();
        //    dt.Columns.Add("CustGroupCode", typeof(String));
        //    dt.Columns.Add("BranchCode", typeof(String));
        //    dt.Columns.Add("OrderNumber", typeof(String));
        //    dt.Columns.Add("LineNumber", typeof(String));

        //    for (int i = 0; i < arrResultSend.Length; i++)
        //    {
        //        string[] arr = arrResultSend[i].Split('|');

TTS/Views/Process/ReturnCompany.cshtml
@model IEnumerable<TTS.Models.ReturnCompanyModel>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "ยืนยันการส่งสินค้าคืนบริษัท";
    ViewBag.PageTitle = "ยืนยันการส่งสินค้าคืนบริษัท";
    ViewBag.PageDesc = "Return to Company";
}


@if (ViewContext.RouteData.Values["bid"] == null)
{
    <div ng-controller="ProcessController">

        <div class="panel-group" id="accordion" role="tablist">
            <div class="panel panel-success">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title inline">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            <i class="fa fa-search"></i> ตัวเลือกค้นหา
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        @using (Html.BeginForm("ReturnCompany", "Process", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            <div class="form-group form-group-sm">
                                <label for="inputPassword3" class="col-sm-2 control-label">วันที่เริ่ม</label>
                                <div class="col-sm-10">
                                    <div class="span5 col-md-10" id="sandbox-container" style="padding-left: 0;">
                                        <div class="input-daterange input-group" id="Div1">
                                            <input type="text" class="input-sm form-control" id="period_start" ng-model="period_start" name="period_start" placeholder="เลือกวันที่เริ่ม" />
                                            <span class="input-group-addon">ถึง</span>
                                            <input type="text" class="input-sm form-control" id="period_end" ng-model="period_end" name="period_end" placeholder="เลือกวันที่สิ้นสุด" />
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group form-group-sm">
                                <label for="inputPassword3" class="col-sm-2 control-label">รหัสกลุ่มลูกค้า</label>
                                <div class="col-sm-4">
                                    <select name="custCode" ng-model="custCodeList" ng-change="custCodeList_OnChange()" class="form-control  js-select2-1">
                                        <option value="">แสดงทั้งหมด</option>
                                        <option ng-repeat="lsCustGroup in cList" value="{{lsCustGroup.CustGroupCode}}">{{lsCustGroup.Description}}</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group form-group-sm">

                                <label for="inputPassword3" class="col-sm-2 control-label">รหัสสาขา <i id="div_spin" class="fa fa-spinner " style="display: none;"></i></label>
                                <div class="col-sm-8">

                                    <select id="lsBranch" name="branch" ng-model="branchList" class="form-control ">
                                        <option value="">แสดงทั้งหมด</option>
                                        <option ng-repeat="lsBranch in baList" value="{{lsBranch.BranchId}}">{{lsBranch.BranchName}}</option>
                                    </select>
                                </div>
                                <div class="col-sm-2">

                                </div>
                            </div>

                            <div class="form-group" style="margin-bottom:0;">
                                <div class="col-md-3 text-left"></div>
                                <div class="col-md-6 text-center">
                                    <button type="button" class="btn btn-primary btn-sm" id="btnSearchSalesOrder" ng-model="btnSearch" ng-click="getBranchFromReturnCompany()"><i class="fa fa-search"></i> แสดง</button>
                                </div>
                                <div class="col-md-3 text-right"></div>
                            </div>
                        }


                        <div ng-repeat="alert in alerts" ng-show="alert.show">
                            <alert type="alert.type" close="closeAlert($index)">{{alert.msg}}</alert>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        @using (Html.BeginForm("ReturnCompany_Send", "Process", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <table id="tbSalesOrder" class="table table-bordered table-striped" ng-init="getBranchFromReturnCompany()">
                <thead>
                    <tr>
                        <th>กลุ่มลูกค้า</th>
                        <th>รหัสสาขา</th>
                        <th>สาขา</th>
                        <th class="nosort" width="60">ยืนยัน</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-model="trBranchFromSalesOrder" ng-repeat="lsBranch in BranchFromSalesOrderList" sales-order-repeat-directive>
                        <td>{{ lsBranch.Description }}</td>
                        <td>{{ lsBranch.BranchCode }}</td>
                        <td><a href="ReturnCompany/{{ lsBranch.BranchCode }}/{{ period_start }}/{{ period_end }}">{{ lsBranch.CustNameThai }} @*<span class="badge">{{ lsBranch.RecordsPerGroup }}</span>*@</a></td>
                        <td align="center"><input type="checkbox" name="chk[]" ng-model="lsBranch.val" value="{{ lsBranch.CustGroupCode }}|{{ lsBranch.BranchCode }}|{{ period_start }}|{{ period_end }}" /></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" style="text-align:right;">
                            <a class="btn btn-success btn-xs link_Send" name="btn_SendToHost" href="#" role="button" title="Send to host" ng-show="HOChoosed()"><i class="fa fa-upload"></i> ส่งข้อมูล HO</a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        }

    </div>

    @section Scripts
{
        <script src="~/Scripts/app/ProcessController.js"></script>
        <script src="~/Scripts/app/ReturnCompany.js"></script>
        <script language="javascript">
            $(document).ready(function () {
                var d = new Date();
                var currDate = d.getDate();
                var currMonth = d.getMonth();
                var currYear = d.getFullYear();
                var startDate = currDate + "/" + currMonth + "/" + currYear;

                $('#sandbox-container .input-daterange').datepicker({
                    defaultDate: startDate,
                    format: "yyyy-mm-dd",
                    startView: 1,
                    todayBtn: true,
                    language: "th",
                    orientation: "top auto",
                    autoclose: true,
                    multidate: false
                });

                //$('#btnSendData').click(function () {
                //    $("#loader-wrapper").show();
                //});

                $("#chkAll").change(function () {
                    $(".chkbox").prop('checked', $(this).prop("checked"));
                });
            });
        </script>

        <script src="~/Scripts/Script_Action.js"></script>
    }

}
else
{


    <div class="table-responsive">
        @Html.Grid(Model).Columns(columns =>
                    {

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link =>
                                    @<a class="btn btn-warning btn-xs link_Edit" name="btn_Edit" id="lnEdit-@Html.Encode(link.OrderNumber)" href="@Url.Action("ReturnCompany_Edit", "Process", new
                                                                                                  {
                                                                                                      i = link.Id
                                                                                                  }, null)" role="button" title="แก้ไข"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>)
                                        .Titled("แก้ไข")
                                        .Css("text-center").Css("nosort");

                        columns.Add()
                                .Encoded(false)
                                .Sanitized(false)
                                .SetWidth(25)
                                .RenderValueAs(link => @<a class="btn btn-danger btn-xs link_delete" name="btn_Delete" id="ln-@Html.Encode(link.OrderNumber)" href="@Url.Action("ReturnCompany_Delete", "Process", new
                                                                                          {
                                                                                              i = link.Id
                                                                                          }, null)" role="button" title="ลบ"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>)
                                .Titled("ลบ")
                                .Css("text-center").Css("nosort");

                        columns.Add(s => s.OrderNumber).Titled("เลขที่บิล");
                        columns.Add(s => s.OrderDate).Titled("วันที่ส่งคืน").Format("{0:dd/MM/yyyy}");
                        columns.Add(s => s.WHCode).Titled("คลังปลายทาง");
                        columns.Add(s => s.ProductId).Titled("รหัสสินค้า");
                        columns.Add(s => s.Size).Titled("ขนาด");

                        columns.Add(s => s.Qty).Titled("ปริมาณ");
                        //columns.Add(s => s.PriceTotal).Titled("ราคาป้าย").Format("{0:n2}");
                        columns.Add(s => s.ApproveBy).Titled("ผู้สั่งโอน");
                        columns.Add(s => s.Reason).Titled("เหตุผล");
                        columns.Add(s => s.IsExport).Titled("Export Status").Css("text-center");
                    })

    </div>
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-danger" role="button" onclick="window.history.back()"><i class="fa fa-backward"></i> กลับ</a>
        </div>
        <div class="col-md-6"></div>
    </div>

    @section Scripts2
    {
        <script language="javascript">
            $(function () {
                var oTable = $('.table').DataTable({
                    lengthMenu: [[10, 20, 50, 100, -1], [10, 20, 50, 100, "All"]],
                    pageLength: 20,
                    "autoWidth": false,
                    "aaSorting": [[2, 'asc']],
                    "dom": 'rt<"row"<"col-md-6"li><"col-md-6"p>> <"clear">',
                    'aoColumnDefs': [{
                        'bSortable': false,
                        'aTargets': ['nosort']
                    }]
                });
            });
        </script>

        <script src="~/Scripts/Script_Action.js"></script>
    }
}

TTS/Views/Process/ReturnCompany_Edit.cshtml
@model TTS.Models.ReturnCompanyModel

@{
    ViewBag.Title = "แก้ไขข้อมูลส่งสินค้าคืนบริษัท";
    ViewBag.PageTitle = "แก้ไขข้อมูลส่งสินค้าคืนบริษัท";
    ViewBag.PageDesc = "";
}

@if (Request.QueryString["msg"] != null)
{
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>บันทึกข้อมูลไม่สำเร็จ!</strong> : @Request.QueryString["msg"].ToString() 
    </div>
}

<div ng-controller="ProcessController_ReturnEdit">
    <div id="panelEditForm">
        @using (Html.BeginForm("ReturnCompany_Update", "Process", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.OrderNumber)</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="OrderNumber" ng-model="OrderNumber" value="{{ OrderNumber }}" readonly />
                </div>

                <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.ProductId)</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="ProductId" ng-model="ProductId" value="{{ ProductId }}" readonly />
                </div>

                <label for="input2" class="col-sm-1 control-label">@Html.LabelFor(a => a.Size)</label>
                <div class="col-sm-1">
                    <input type="text" class="form-control" name="Size" ng-model="Size" value="{{ Size }}" readonly />
                </div>
            </div>

            <div class="form-group">
                <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.WHCode)</label>
                <div class="col-sm-3">
                    <select name="WHCode" ng-model="WHCode" class="form-control">
                        <option ng-repeat="lsWHlist in WHlists" value="{{lsWHlist.WHCode}}">{{lsWHlist.WHCode}}</option>
                    </select>
                </div>

                <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.ProductName)</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" name="ProductName" ng-model="ProductName" value="{{ProductName }}" readonly />
                </div>
            </div>

            <div class="form-group">
                <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.ApproveBy)</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="ApproveBy" ng-model="ApproveBy" value="{{ApproveBy }}" readonly />
                </div>

                <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.RTPrice)</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" name="RTPrice" ng-model="RTPrice" value="{{RTPrice }}" readonly />
                </div>
            </div>

            <div class="form-group">
                <label for="input1" class="col-sm-2 control-label">@Html.LabelFor(a => a.Reason)</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="Reason" ng-model="Reason" value="{{Reason }}" readonly />
                </div>

                <label for="input2" class="col-sm-2 control-label">@Html.LabelFor(a => a.Qty)</label>
                <div class="col-sm-5">
                    <input type="number" class="form-control" name="Qty" ng-model="Qty" value="{{Qty }}" />
                </div>
            </div>


            <input type="hidden" name="Id" ng-model="Id" value="{{ Id }}" />
            <input type="hidden" name="BranchCode" ng-model="BranchCode" value="{{ BranchCode }}" />
            <input type="hidden" name="InvoiceNumber" ng-model="InvoiceNumber" value="{{InvoiceNumber }}" />
            <input type="hidden" name="RefNumber" ng-model="RefNumber" value="{{ RefNumber }}" />
            <input type="hidden" name="IsExport" ng-model="IsExport" value="{{ IsExport }}" />


            <div class="form-group">
                <div class="col-sm-12 text-center">
                    @*<button type="button" class="btn btn-success" ng-click="btnSaveSalesOrder_OnClick()"><i class="fa fa-floppy-o"></i> บันทึก</button>*@
                    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> บันทึก</button>
                    <a class="btn btn-danger" role="button" onclick="window.history.back()"><i class="fa fa-times"></i> ยกเลิก</a>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{
    <script src="~/Scripts/app/ProcessController.js"></script>
    <script src="~/Scripts/app/ReturnCompany.js"></script>
    <script language="javascript">
        $(document).ready(function () {

            $(function () {
                $("[data-url]").click(function () {
                    location.href = $(this).data("url");
                });
            });
        });
    </script>
}

TTS/Views/Process/SalesOrder_Discount.cshtml
@{
    Layout = null;
    //ViewBag.Title = "SalesOrder_Discount";
}

<div id="panelDiscount" style="display:none;">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Discount</h3>
        </div>
        <div class="panel-body">

            <form name="frmDiscount" class="form-horizontal" ng-submit="addDiscount()" novalidate>
                <div class="form-group">
                    <label for="input1" class="col-sm-2 control-label">ประเภทบัตร/คูปอง</label>
                    <div class="col-sm-10">
                        @*@Html.TextBoxFor(a => a.cardType, new { @class = "form-control", @readonly = "true" })*@
                        <div>
                            <select ng-model="Couponlist" ng-change="Couponlist_OnChange()" class="form-control">
                                @*<option value="">-- Select a Book --</option>*@
                                <option ng-repeat="lsCoupon in Couponlists" value="{{lsCoupon.id}}">{{lsCoupon.name}}</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="input1" class="col-sm-2 control-label">ส่วนลด(%)</label>
                    <div class="col-sm-10">
                        @*@Html.TextBoxFor(a => a.discountPer, new { @class = "form-control", @readonly = "true" })*@
                        <input type="number" class="form-control" name="name" ng-model="dDiscountPer" required />
                    </div>
                </div>

                <div class="form-group">
                    <label for="input1" class="col-sm-2 control-label">ส่วนลด(บาท)</label>
                    <div class="col-sm-10">
                        @*@Html.TextBoxFor(a => a.discount, new { @class = "form-control", @readonly = "true" })*@
                        <input type="number" class="form-control" name="name" ng-model="dDiscountBaht" required />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12 text-center">
                        <button type="submit" class="btn btn-success" ng-disabled="frmDiscount.$invalid">
                            <i class="fa fa-plus"></i> เพิ่ม
                        </button>
                    </div>
                </div>

                <hr />
            </form>


            @using (Html.BeginForm("Discount_Update", "Process", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="200">ลำดับ</th>
                                    <th>ส่วนลด (%)</th>
                                    <th>ส่วนลด (บาท)</th>
                                    <th width="25" align="center">ลบ</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="row in rowsDiscount">
                                    <td>{{row.No}}</td>
                                    <td>{{row.DiscountPer}}</td>
                                    <td>{{row.DiscountBaht}}</td>
                                    <td align="center">
                                        <a class="btn btn-danger btn-xs link_delete" name="btn_Delete" role="button" title="ลบ" ng-click="removeDiscount($index)"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button type="button" class="btn btn-success btnDiscountForm"><i class="fa fa-check"></i> ตกลง</button>
                        @*<button type="button" class="btn btn-warning"><i class="fa fa-floppy-o"></i> ลบ</button>*@
                        @*<button type="button" class="btn btn-danger btnDiscountForm"><i class="fa fa-close"></i> ออก</button>*@
                    </div>
                </div>

            }

        </div>
    </div>

</div>

TTS/Views/Process/SalesOrder_New.cshtml
@{
    ViewBag.Title = "SalesOrder_New";
}

<h2>SalesOrder_New</h2>

TTS/Views/Process/Sales_Confirm.cshtml
@{
    ViewBag.Title = "แก้ไขและยืนยันข้อมูลการขายสินค้า";
    ViewBag.PageTitle = "แก้ไขและยืนยันข้อมูลการขายสินค้า";
    ViewBag.PageDesc = "Edit / Confirm - Sales";
}